# Generated by Django 6.1.1 on 2026-09-10 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BORROWED', 'Borrowed'), ('DAMAGED', 'Damaged'), ('DESTROY', 'Destroy')], default='AVAILABLE', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.item')),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=100)),
            ],
            bases=('catalog.item',),
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.item')),
                ('artist', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            bases=('catalog.item',),
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.item')),
                ('type', models.CharField(blank=True, max_length=100)),
                ('age', models.CharField(blank=True, max_length=20)),
            ],
            bases=('catalog.item',),
        ),
    ]
